### ISSUE TITLE
An idea regarding the crash bug

### ISSUE THREAD

**Issue by SzotsGabor** [Ciekce/Polaris#20] opened 2023-05-05 17:19 UTC
Hi Conor,

Could it be an issue with Windows 11?

Gabor Szots
CCRL testing group

**Comment by Ciekce** [comment] 2023-05-06 13:29
Hi Gabor, thanks for the idea :)

unfortunately, most of the crashes I've seen have been on linux openbench workers, and my primary system is win11 :/. I'm pretty sure it's a threading issue though, and I have a general idea of where to look

have you experienced crashes on windows 11? if so, which cpu are you using, and is it possible to get a pgn? a log of stderr would also be very useful, although I recognise that it's unlikely your gui would save one

**Comment by SzotsGabor** [comment] 2023-05-06 13:37
I have not tested the latest version yet. With previous versions I had no crashes.

I have Windows 11 and my CPU is i7-12700K.

**Comment by Ciekce** [comment] 2023-05-09 03:43
Closing, as the issue is fixed :)

**Closed by Ciekce** 2023-05-09 03:43 UTC
